// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP41ZS9oOgyBfUBXqLjQ_JaQLmZqkqsRY',
    appId: '1:968340329961:web:9603c31026084e291ce778',
    messagingSenderId: '968340329961',
    projectId: 'kaskredit-bb294',
    authDomain: 'kaskredit-bb294.firebaseapp.com',
    storageBucket: 'kaskredit-bb294.firebasestorage.app',
    measurementId: 'G-N7W5WRDWKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDajvQe6TBqeOHwKEhwkd_-_YNFW87Fvfo',
    appId: '1:968340329961:android:21abe31cf0b3799f1ce778',
    messagingSenderId: '968340329961',
    projectId: 'kaskredit-bb294',
    storageBucket: 'kaskredit-bb294.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQoKlDgIuL4xJhG_g6fbFyYsE1DaMdjQU',
    appId: '1:968340329961:ios:0f613581ede490c31ce778',
    messagingSenderId: '968340329961',
    projectId: 'kaskredit-bb294',
    storageBucket: 'kaskredit-bb294.firebasestorage.app',
    iosBundleId: 'com.example.kaskredit1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQoKlDgIuL4xJhG_g6fbFyYsE1DaMdjQU',
    appId: '1:968340329961:ios:0f613581ede490c31ce778',
    messagingSenderId: '968340329961',
    projectId: 'kaskredit-bb294',
    storageBucket: 'kaskredit-bb294.firebasestorage.app',
    iosBundleId: 'com.example.kaskredit1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP41ZS9oOgyBfUBXqLjQ_JaQLmZqkqsRY',
    appId: '1:968340329961:web:433764dba1e9ab5a1ce778',
    messagingSenderId: '968340329961',
    projectId: 'kaskredit-bb294',
    authDomain: 'kaskredit-bb294.firebaseapp.com',
    storageBucket: 'kaskredit-bb294.firebasestorage.app',
    measurementId: 'G-REG3M4MZ46',
  );
}
